name: Build APK

on:
  push:
    branches:
      - main  # Change if your default branch is different
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          pip install flet pandas pyperclip openpyxl  # Install required libraries
          # Add any additional libraries if needed

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'  # Specify a specific version of Flutter

      - name: Build APK
        run: |
          # Navigate to the Android directory and build the APK
          cd android
          ./gradlew assembleDebug  # Build the APK (you can change to assembleRelease for release builds)

      - name: Upload APK
        uses: actions/upload-artifact@v4  # Updated to version 4
        with:
          name: apk
          path: android/app/build/outputs/apk/debug/app-debug.apk  # Adjust the path if needed
