name: Build APK

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12.2
  FLUTTER_VERSION: 3.22.2
  ANDROID_HOME: ${{ github.workspace }}/android-sdk

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3.2.1
        with:
          cmdline-tools-version: '9.0'
          accept-android-sdk-licenses: true

      - name: Build Android APK using automated-build-android-app-with-github-action
        uses: amirisback/automated-build-android-app-with-github-action@2.2.4
        with:
          android_home: ${{ github.workspace }}/android-sdk
          jdk_version: 17
          gradle_version: '7.4'  # (optional, if you want a specific Gradle version)

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: apk-build-artifact
          path: build/apk
          if-no-files-found: warn
          overwrite: false
