name: Build APK

on:
  push:
    branches:
      - main  # Change if your default branch is different
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          pip install flet pandas pyperclip openpyxl  # Install required libraries

      - name: Build APK
        run: |
          # Build the APK using Flet
          python -m flet build --target=apk  # Adjust if necessary based on your Flet setup

      - name: Upload APK
        uses: actions/upload-artifact@v4  # Updated to version 4
        with:
          name: apk
          path: build/*.apk  # Adjust the path if the APK output location is different
