name: Build Flet APK

on:
  push:
    branches: [main]

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install flet pandas pyperclip openpyxl

      - name: Set Up Flutter
        uses: actions/setup-flutter@v2
        with:
          flutter-version: 'stable'

      - name: Set Up Android SDK
        uses: actions/setup-android@v3
        with:
          api-level: 33
          sdk-root: "$HOME/Android/Sdk"

      - name: Configure Environment Variables
        run: |
          export PATH="$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/emulator:$ANDROID_SDK_ROOT/tools:$PATH"

      - name: Build APK
        run: |
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: build/*.apk
